"""
Pydantic models for the FastAPI service.

This module defines all request and response schemas for the Research Framework API.
Pydantic models provide automatic validation, serialization, and OpenAPI schema
generation for the API endpoints.

Model Categories:
    - Enums: Status codes, roles, and configuration options
    - Agent Models: Definitions for research agents
    - Research Models: Request/response for research operations
    - Search Models: Web search request/response
    - Citation Models: Citation processing request/response
    - Health Models: API health and info responses
    - Error Models: Standardized error responses

Example Usage:
    >>> from api.models import ResearchRequest, ResearchStatus
    >>> request = ResearchRequest(
    ...     hypothesis="AI will transform healthcare",
    ...     max_agents=3
    ... )
    >>> print(request.model_dump())
"""

from datetime import datetime
from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


# ============================================================================
# Enums
# ============================================================================
# Enums define fixed sets of values for type safety and API documentation.
# Using str as base class allows JSON serialization as strings.

class ResearchStatus(str, Enum):
    """
    Status of a research task throughout its lifecycle.

    States:
        PENDING: Task created but not yet started
        RUNNING: Task is currently being processed
        COMPLETED: Task finished successfully
        FAILED: Task encountered an error
        CANCELLED: Task was cancelled by user or system
    """
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AgentRole(str, Enum):
    """
    Predefined agent role types in the research framework.

    Roles:
        LEAD_RESEARCHER: Orchestrates multiple agents and synthesizes findings
        RESEARCH_AGENT: Specialized investigator for specific domains
        CITATION_AGENT: Adds source citations to research content
    """
    LEAD_RESEARCHER = "lead_researcher"
    RESEARCH_AGENT = "research_agent"
    CITATION_AGENT = "citation_agent"


class CitationStyle(str, Enum):
    """
    Supported citation formatting styles.

    Styles:
        SIMPLE: Basic format - [1] Title (URL)
        APA: American Psychological Association style
        MLA: Modern Language Association style
        CHICAGO: Chicago Manual of Style
    """
    SIMPLE = "simple"
    APA = "apa"
    MLA = "mla"
    CHICAGO = "chicago"


# ============================================================================
# Agent Models
# ============================================================================
# Models for defining and reporting on research agents.

class AgentDefinition(BaseModel):
    """
    Definition for a custom research agent.

    This model allows users to define specialized agents with specific
    focus areas for their research investigation. Each agent will
    investigate aspects related to their defined focus.

    Attributes:
        name: Human-readable agent name (e.g., "Market Analyst")
        focus: Research focus area describing what the agent investigates
        tools: List of tool names the agent can use (default: web_search)

    Example:
        >>> agent = AgentDefinition(
        ...     name="Tech Expert",
        ...     focus="technical feasibility and implementation challenges"
        ... )
    """
    name: str = Field(
        ...,
        description="Agent name",
        example="Market Analyst",
        min_length=1,
        max_length=100
    )
    focus: str = Field(
        ...,
        description="Research focus area",
        example="market trends and competition",
        min_length=1,
        max_length=500
    )
    tools: Optional[List[str]] = Field(
        default=["web_search"],
        description="Tools available to the agent"
    )

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "name": "Tech Expert",
                "focus": "technical feasibility and implementation",
                "tools": ["web_search"]
            }
        }


class AgentResultResponse(BaseModel):
    """
    Response model containing results from a single research agent.

    This model represents the output of one agent's research execution,
    including findings, sources, and execution metadata.

    Attributes:
        agent_id: Unique identifier for the agent instance
        agent_name: Human-readable agent name
        status: Execution status (completed, failed, etc.)
        content: Full text content generated by the agent
        findings: List of structured finding objects
        sources: List of source references used
        duration_seconds: Time taken for agent execution
        token_usage: Token counts for API usage tracking
    """
    agent_id: str = Field(..., description="Unique agent identifier")
    agent_name: str = Field(..., description="Agent display name")
    status: str = Field(..., description="Execution status")
    content: str = Field(..., description="Generated content")
    findings: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Structured findings list"
    )
    sources: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Sources referenced"
    )
    duration_seconds: Optional[float] = Field(
        None,
        description="Execution duration in seconds"
    )
    token_usage: Dict[str, int] = Field(
        default_factory=dict,
        description="Token usage statistics"
    )


# ============================================================================
# Research Request Models
# ============================================================================
# Models for initiating research operations.

class ResearchRequest(BaseModel):
    """
    Request model for starting a multi-agent research investigation.

    This is the primary request model for the /research endpoint.
    It supports both simple research (hypothesis only) and complex
    investigations with custom agents and specific questions.

    Attributes:
        hypothesis: Main research hypothesis or question to investigate
        research_questions: Optional specific questions to address
        custom_agents: Optional custom agent definitions (max 5)
        max_agents: Maximum number of agents to use (1-5)
        model_tier: Model configuration tier (default, budget, premium, fast)
        include_citations: Whether to add citations to final report
        citation_style: Style for citation formatting

    Example:
        >>> request = ResearchRequest(
        ...     hypothesis="AI will transform healthcare by 2030",
        ...     custom_agents=[
        ...         AgentDefinition(name="Tech Analyst", focus="AI technology"),
        ...         AgentDefinition(name="Policy Analyst", focus="regulations")
        ...     ],
        ...     max_agents=2,
        ...     include_citations=True
        ... )
    """
    hypothesis: str = Field(
        ...,
        description="The main research hypothesis or question",
        example="Artificial intelligence will significantly improve medical diagnosis accuracy by 2030",
        min_length=10,
        max_length=1000
    )
    research_questions: Optional[List[str]] = Field(
        default=None,
        description="Specific research questions to investigate",
        example=["What AI techniques are used in medical diagnosis?"]
    )
    custom_agents: Optional[List[AgentDefinition]] = Field(
        default=None,
        description="Custom agent definitions (max 5)",
        max_length=5
    )
    max_agents: int = Field(
        default=3,
        ge=1,
        le=5,
        description="Maximum number of agents to use"
    )
    model_tier: str = Field(
        default="default",
        description="Model tier: default, budget, premium, fast"
    )
    include_citations: bool = Field(
        default=True,
        description="Whether to add citations to the final report"
    )
    citation_style: CitationStyle = Field(
        default=CitationStyle.SIMPLE,
        description="Citation style for the report"
    )

    class Config:
        """Pydantic model configuration with example."""
        json_schema_extra = {
            "example": {
                "hypothesis": "AI will transform healthcare diagnostics by 2030",
                "research_questions": [
                    "What AI techniques are currently used?",
                    "What are the barriers to adoption?"
                ],
                "custom_agents": [
                    {"name": "Tech Analyst", "focus": "technical capabilities"},
                    {"name": "Policy Analyst", "focus": "regulatory landscape"}
                ],
                "max_agents": 2,
                "model_tier": "default",
                "include_citations": True,
                "citation_style": "simple"
            }
        }


class QuickSearchRequest(BaseModel):
    """
    Request model for a quick web search operation.

    This lightweight model is used for simple search queries
    without the full research orchestration.

    Attributes:
        query: Search query string
        max_results: Maximum number of results to return (1-20)
        backend: Optional search backend override

    Example:
        >>> request = QuickSearchRequest(
        ...     query="AI in healthcare 2024",
        ...     max_results=10,
        ...     backend="tavily"
        ... )
    """
    query: str = Field(
        ...,
        description="Search query",
        example="AI in healthcare 2024",
        min_length=1,
        max_length=500
    )
    max_results: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of results to return"
    )
    backend: Optional[str] = Field(
        default=None,
        description="Search backend: tavily, brave, serper, bing, duckduckgo"
    )


class CitationRequest(BaseModel):
    """
    Request model for adding citations to content.

    This model is used to process existing content and add
    inline citations based on provided sources.

    Attributes:
        content: The text content to add citations to
        sources: List of source dictionaries with title, url, etc.
        style: Citation formatting style

    Example:
        >>> request = CitationRequest(
        ...     content="AI is transforming healthcare...",
        ...     sources=[{"title": "AI Study", "url": "https://..."}],
        ...     style=CitationStyle.APA
        ... )
    """
    content: str = Field(
        ...,
        description="Content to add citations to",
        min_length=1
    )
    sources: List[Dict[str, Any]] = Field(
        ...,
        description="Available sources for citation"
    )
    style: CitationStyle = Field(
        default=CitationStyle.SIMPLE,
        description="Citation formatting style"
    )


# ============================================================================
# Research Response Models
# ============================================================================
# Models for research operation results.

class ResearchPlanResponse(BaseModel):
    """
    Response model containing the research plan created by Lead Researcher.

    This model represents the strategic plan created before
    research execution begins.

    Attributes:
        hypothesis: The original research hypothesis
        complexity: Assessed complexity level (simple, moderate, complex)
        domains: Identified knowledge domains to investigate
        research_questions: Questions to be investigated
        agent_assignments: How work is distributed among agents
        strategy_notes: Additional strategic considerations
    """
    hypothesis: str = Field(..., description="Original research hypothesis")
    complexity: str = Field(..., description="Complexity assessment")
    domains: List[str] = Field(..., description="Relevant knowledge domains")
    research_questions: List[str] = Field(..., description="Questions to investigate")
    agent_assignments: List[Dict[str, Any]] = Field(
        ...,
        description="Work distribution among agents"
    )
    strategy_notes: str = Field(..., description="Strategic considerations")


class ResearchResponse(BaseModel):
    """
    Complete response model for a finished research investigation.

    This comprehensive model contains all results from a multi-agent
    research operation, including the plan, individual agent results,
    synthesis, and final report.

    Attributes:
        task_id: Unique identifier for this research task
        status: Current status of the research
        hypothesis: Original research hypothesis
        plan: Research plan (if available)
        agent_results: Results from each research agent
        synthesis: Synthesized findings across agents
        final_report: Complete formatted research report
        total_duration_seconds: Total execution time
        total_tokens: Total API tokens used
        estimated_cost: Estimated API cost in USD
        created_at: When the task was created
        completed_at: When the task finished (if completed)
    """
    task_id: str = Field(..., description="Unique task identifier")
    status: ResearchStatus = Field(..., description="Task status")
    hypothesis: str = Field(..., description="Research hypothesis")
    plan: Optional[ResearchPlanResponse] = Field(
        None,
        description="Research plan"
    )
    agent_results: List[AgentResultResponse] = Field(
        default_factory=list,
        description="Individual agent results"
    )
    synthesis: str = Field(..., description="Synthesized findings")
    final_report: str = Field(..., description="Complete research report")
    total_duration_seconds: float = Field(
        ...,
        description="Total execution time in seconds"
    )
    total_tokens: int = Field(..., description="Total tokens used")
    estimated_cost: float = Field(..., description="Estimated cost in USD")
    created_at: datetime = Field(..., description="Task creation timestamp")
    completed_at: Optional[datetime] = Field(
        None,
        description="Task completion timestamp"
    )

    class Config:
        """Pydantic model configuration with example."""
        json_schema_extra = {
            "example": {
                "task_id": "abc123",
                "status": "completed",
                "hypothesis": "AI will transform healthcare",
                "final_report": "# Research Report\n\n...",
                "total_duration_seconds": 45.2,
                "total_tokens": 15000,
                "estimated_cost": 0.025
            }
        }


class ResearchStatusResponse(BaseModel):
    """
    Response model for checking async research task status.

    Used to poll the status of background research tasks.

    Attributes:
        task_id: Unique task identifier
        status: Current task status
        progress: Progress percentage (0.0 to 1.0)
        current_stage: Current execution stage name
        agents_completed: Number of agents finished
        agents_total: Total number of agents
        elapsed_seconds: Time since task started
        message: Optional status message or error
    """
    task_id: str = Field(..., description="Task identifier")
    status: ResearchStatus = Field(..., description="Current status")
    progress: float = Field(
        ...,
        ge=0,
        le=1,
        description="Progress from 0 to 1"
    )
    current_stage: str = Field(..., description="Current execution stage")
    agents_completed: int = Field(..., description="Agents finished")
    agents_total: int = Field(..., description="Total agents")
    elapsed_seconds: float = Field(..., description="Elapsed time")
    message: Optional[str] = Field(None, description="Status message")


# ============================================================================
# Search Response Models
# ============================================================================
# Models for web search results.

class SearchResult(BaseModel):
    """
    A single web search result.

    Represents one item from a search query response.

    Attributes:
        title: Page title
        url: Page URL
        snippet: Text excerpt from the page
        score: Relevance score (0-1, if available)
    """
    title: str = Field(..., description="Page title")
    url: str = Field(..., description="Page URL")
    snippet: str = Field(..., description="Text excerpt")
    score: Optional[float] = Field(None, description="Relevance score")


class SearchResponse(BaseModel):
    """
    Response model for web search queries.

    Contains the search results and metadata about the search.

    Attributes:
        query: Original search query
        backend: Search backend used (tavily, brave, etc.)
        results: List of search results
        result_count: Number of results returned
        answer: AI-generated answer (if available from backend)
    """
    query: str = Field(..., description="Original query")
    backend: str = Field(..., description="Backend used")
    results: List[SearchResult] = Field(..., description="Search results")
    result_count: int = Field(..., description="Number of results")
    answer: Optional[str] = Field(None, description="AI-generated answer")


# ============================================================================
# Citation Response Models
# ============================================================================
# Models for citation processing results.

class CitationResponse(BaseModel):
    """
    Response model for citation processing operations.

    Contains the cited content and statistics about citations added.

    Attributes:
        original_length: Character count of original content
        cited_content: Content with inline citations added
        reference_list: Formatted bibliography/reference section
        citations_added: Total citation markers added
        unique_sources_cited: Number of unique sources referenced
    """
    original_length: int = Field(..., description="Original content length")
    cited_content: str = Field(..., description="Content with citations")
    reference_list: str = Field(..., description="Formatted references")
    citations_added: int = Field(..., description="Citations added")
    unique_sources_cited: int = Field(..., description="Unique sources used")


# ============================================================================
# Health & Info Models
# ============================================================================
# Models for API health checks and framework information.

class HealthResponse(BaseModel):
    """
    API health check response.

    Returns the health status of the API and its components.

    Attributes:
        status: Overall health status ("healthy" or "unhealthy")
        version: API version string
        timestamp: Current server timestamp
        components: Health status of individual components
    """
    status: str = Field(default="healthy", description="Overall status")
    version: str = Field(..., description="API version")
    timestamp: datetime = Field(..., description="Server timestamp")
    components: Dict[str, str] = Field(..., description="Component statuses")


class BackendStatus(BaseModel):
    """
    Status of a search backend.

    Indicates whether a search backend is available and configured.

    Attributes:
        name: Backend name (tavily, brave, etc.)
        available: Whether the backend can be used
        configured: Whether API key is configured
    """
    name: str = Field(..., description="Backend name")
    available: bool = Field(..., description="Is available")
    configured: bool = Field(..., description="Is configured")


class FrameworkInfoResponse(BaseModel):
    """
    Framework information and capabilities response.

    Provides comprehensive information about the framework's
    capabilities and current configuration.

    Attributes:
        name: Framework name
        version: Framework version
        description: Brief description
        available_backends: Search backend availability
        model_tiers: Available model configuration tiers
        max_agents: Maximum agents per research task
        features: List of framework features
    """
    name: str = Field(
        default="Multi-Agent Research Framework",
        description="Framework name"
    )
    version: str = Field(..., description="Version string")
    description: str = Field(..., description="Framework description")
    available_backends: List[BackendStatus] = Field(
        ...,
        description="Search backend status"
    )
    model_tiers: List[str] = Field(..., description="Available model tiers")
    max_agents: int = Field(..., description="Max agents per task")
    features: List[str] = Field(..., description="Framework features")


# ============================================================================
# Error Models
# ============================================================================
# Standardized error response models.

class ErrorResponse(BaseModel):
    """
    Standardized error response model.

    Used for all API error responses to provide consistent
    error information to clients.

    Attributes:
        error: Error type or message
        detail: Detailed error description
        code: Machine-readable error code
        timestamp: When the error occurred
    """
    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(None, description="Detailed description")
    code: Optional[str] = Field(None, description="Error code")
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="Error timestamp"
    )


class ValidationErrorResponse(BaseModel):
    """
    Validation error response for request validation failures.

    Contains details about which fields failed validation.

    Attributes:
        error: Always "Validation Error"
        details: List of validation error details
    """
    error: str = Field(default="Validation Error", description="Error type")
    details: List[Dict[str, Any]] = Field(..., description="Validation details")
